### ISSUE TITLE
server port number

### ISSUE THREAD

**Issue by rachaelcodes** [foundersandcoders/ws-cookies#20] opened 2017-08-07 13:41 UTC
hi - just a really quick one. In the readme, the server is named as `4000`, but the exercise sends me to `3000`.

**Comment by jsms90** [comment] 2017-08-07 16:54
duplicate of issue #16 & seems to have been solved via PR #17 (which was merged a few hours before this issue was raised)

I'm confused :confused:

**Closed as completed** 2017-08-08 13:43 UTC
